/**
 * Created by chao on 2016/6/21.
 */
define(['angular'], function(angular) {
	var webpc = angular.module('mdAirCitys', []);
	webpc.constant('airCitys', {
		'citys': {
			"Hot":[{
				"cityId": "8a88b3ce4ef2ded8014ef2e0e48a000e",
				"text": "北京",
				"countryName": "中国",
				"flightCityCode": "222",
				"hotCityFlag": null,
				"py": "Beijing",
				"stateName": null
			},{
				"cityId": "3cfa8317631e48d1b8ed7e88f0077cbf",
				"text": "上海",
				"countryName": "中国",
				"flightCityCode": "111",
				"hotCityFlag": null,
				"py": "ShangHai",
				"stateName": null
			},{
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4d80092",
				"text": "天津",
				"countryName": "中国",
				"flightCityCode": "TSN",
				"hotCityFlag": null,
				"py": "Tianjin",
				"stateName": null
			},{
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4fa00c2",
				"text": "重庆",
				"countryName": "中国",
				"flightCityCode": "CKG",
				"hotCityFlag": null,
				"py": "Chongqing",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e496001e",
				"text": "大连",
				"countryName": "中国",
				"flightCityCode": "DLC",
				"hotCityFlag": null,
				"py": "Dalian",
				"stateName": null
			},{
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4ce007e",
				"text": "青岛",
				"countryName": "中国",
				"flightCityCode": "TAO",
				"hotCityFlag": null,
				"py": "Qingdao",
				"stateName": null
			},{
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4e100a3",
				"text": "西安",
				"countryName": "中国",
				"flightCityCode": "XIY",
				"hotCityFlag": null,
				"py": "Xian",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4c70074",
				"text": "南京",
				"countryName": "中国",
				"flightCityCode": "NKG",
				"hotCityFlag": null,
				"py": "Nanjing",
				"stateName": null
			},{
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4d6008d",
				"text": "苏州",
				"countryName": "中国",
				"flightCityCode": "SZV",
				"hotCityFlag": null,
				"py": "Suzhou",
				"stateName": null
			}],
			"A": [{
				"cityId": "8a88b3ce4ef2ded8014ef2e0e47b0000",
				"text": "阿尔山",
				"countryName": "中国",
				"flightCityCode": "YIE",
				"hotCityFlag": null,
				"py": "AErShan",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4800001",
				"text": "阿克苏",
				"countryName": "中国",
				"flightCityCode": "AKU",
				"hotCityFlag": null,
				"py": "Akesu",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4810002",
				"text": "阿勒泰",
				"countryName": "中国",
				"flightCityCode": "AAT",
				"hotCityFlag": null,
				"py": "Aletai",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4810003",
				"text": "阿里",
				"countryName": "中国",
				"flightCityCode": "NGQ",
				"hotCityFlag": null,
				"py": "ALi",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4820004",
				"text": "安康",
				"countryName": "中国",
				"flightCityCode": "AKA",
				"hotCityFlag": null,
				"py": "Ankan",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4840005",
				"text": "安庆",
				"countryName": "中国",
				"flightCityCode": "AQG",
				"hotCityFlag": null,
				"py": "Anqing",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4840006",
				"text": "安顺",
				"countryName": "中国",
				"flightCityCode": "AVA",
				"hotCityFlag": null,
				"py": "Anshun",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4850007",
				"text": "鞍山",
				"countryName": "中国",
				"flightCityCode": "AOG",
				"hotCityFlag": null,
				"py": "Anshan",
				"stateName": null
			}],
			"B": [{
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4860008",
				"text": "巴彦淖尔",
				"countryName": "中国",
				"flightCityCode": "RLK",
				"hotCityFlag": null,
				"py": "BaYanZhuoEr",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4870009",
				"text": "百色",
				"countryName": "中国",
				"flightCityCode": "AEB",
				"hotCityFlag": null,
				"py": "Baise",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e487000a",
				"text": "蚌埠",
				"countryName": "中国",
				"flightCityCode": "BFU",
				"hotCityFlag": null,
				"py": "Bengbu",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e488000b",
				"text": "包头",
				"countryName": "中国",
				"flightCityCode": "BAV",
				"hotCityFlag": null,
				"py": "Baotou",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e489000c",
				"text": "保山",
				"countryName": "中国",
				"flightCityCode": "BSD",
				"hotCityFlag": null,
				"py": "Baoshan",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e489000d",
				"text": "北海",
				"countryName": "中国",
				"flightCityCode": "BHY",
				"hotCityFlag": null,
				"py": "Beihai",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e48a000e",
				"text": "北京",
				"countryName": "中国",
				"flightCityCode": "222",
				"hotCityFlag": null,
				"py": "Beijing",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e48b000f",
				"text": "北京(首都)",
				"countryName": "中国",
				"flightCityCode": "PEK",
				"hotCityFlag": null,
				"py": "BeiJingCapital",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e48d0010",
				"text": "北京(南苑)",
				"countryName": "中国",
				"flightCityCode": "NAY",
				"hotCityFlag": null,
				"py": "BeiJingNanYuan",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e48e0011",
				"text": "博乐",
				"countryName": "中国",
				"flightCityCode": "BPL",
				"hotCityFlag": null,
				"py": "BoLe",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4ff00c8",
				"text": "毕节",
				"countryName": "中国",
				"flightCityCode": "BFJ",
				"hotCityFlag": null,
				"py": "BiJie",
				"stateName": null
			}],
			"C": [{
				"cityId": "8a88b3ce4ef2ded8014ef2e0e48f0012",
				"text": "昌都",
				"countryName": "中国",
				"flightCityCode": "BPX",
				"hotCityFlag": null,
				"py": "Chandu",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e48f0013",
				"text": "长白山",
				"countryName": "中国",
				"flightCityCode": "NBS",
				"hotCityFlag": null,
				"py": "Changbaishan",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4900014",
				"text": "长春",
				"countryName": "中国",
				"flightCityCode": "CGQ",
				"hotCityFlag": null,
				"py": "Changchun",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4900015",
				"text": "长沙",
				"countryName": "中国",
				"flightCityCode": "CSX",
				"hotCityFlag": null,
				"py": "Changsha",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4910016",
				"text": "长治",
				"countryName": "中国",
				"flightCityCode": "CIH",
				"hotCityFlag": null,
				"py": "Changzhi",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4920017",
				"text": "常德",
				"countryName": "中国",
				"flightCityCode": "CGD",
				"hotCityFlag": null,
				"py": "Changde",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4920018",
				"text": "常州",
				"countryName": "中国",
				"flightCityCode": "CZX",
				"hotCityFlag": null,
				"py": "Changzhou",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4930019",
				"text": "朝阳",
				"countryName": "中国",
				"flightCityCode": "CHG",
				"hotCityFlag": null,
				"py": "Chaoyang",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e493001a",
				"text": "成都",
				"countryName": "中国",
				"flightCityCode": "CTU",
				"hotCityFlag": null,
				"py": "Chengdu",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e494001b",
				"text": "赤峰",
				"countryName": "中国",
				"flightCityCode": "CIF",
				"hotCityFlag": null,
				"py": "Chifeng",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4fa00c2",
				"text": "重庆",
				"countryName": "中国",
				"flightCityCode": "CKG",
				"hotCityFlag": null,
				"py": "Chongqing",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4fe00c7",
				"text": "池州",
				"countryName": "中国",
				"flightCityCode": "JUH",
				"hotCityFlag": null,
				"py": "ChiZhou",
				"stateName": null
			}],
			"D": [{
				"cityId": "8a88b3ce4ef2ded8014ef2e0e495001c",
				"text": "达县",
				"countryName": "中国",
				"flightCityCode": "DAX",
				"hotCityFlag": null,
				"py": "Daxian",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e495001d",
				"text": "大理",
				"countryName": "中国",
				"flightCityCode": "DLU",
				"hotCityFlag": null,
				"py": "Dali",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e496001e",
				"text": "大连",
				"countryName": "中国",
				"flightCityCode": "DLC",
				"hotCityFlag": null,
				"py": "Dalian",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e496001f",
				"text": "大庆",
				"countryName": "中国",
				"flightCityCode": "DQA",
				"hotCityFlag": null,
				"py": "Daqing",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4970020",
				"text": "大同",
				"countryName": "中国",
				"flightCityCode": "DAT",
				"hotCityFlag": null,
				"py": "Datong",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4970021",
				"text": "丹东",
				"countryName": "中国",
				"flightCityCode": "DDG",
				"hotCityFlag": null,
				"py": "Dandong",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4980022",
				"text": "德宏芒市",
				"countryName": "中国",
				"flightCityCode": "LUM",
				"hotCityFlag": null,
				"py": "Dehongmangshi",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4990023",
				"text": "迪庆香格里拉",
				"countryName": "中国",
				"flightCityCode": "DIG",
				"hotCityFlag": null,
				"py": "Diqingxianggelila",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4990024",
				"text": "东营",
				"countryName": "中国",
				"flightCityCode": "DOY",
				"hotCityFlag": null,
				"py": "Dongying",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e49a0025",
				"text": "敦煌",
				"countryName": "中国",
				"flightCityCode": "DNH",
				"hotCityFlag": null,
				"py": "Dunhuang",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4ff00c9",
				"text": "稻城亚丁",
				"countryName": "中国",
				"flightCityCode": "DCY",
				"hotCityFlag": null,
				"py": "DaoChengYaDing",
				"stateName": null
			}],
			"E": [{
				"cityId": "8a88b3ce4ef2ded8014ef2e0e49a0026",
				"text": "鄂尔多斯",
				"countryName": "中国",
				"flightCityCode": "DSN",
				"hotCityFlag": null,
				"py": "Eerduosi",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e49b0027",
				"text": "恩施",
				"countryName": "中国",
				"flightCityCode": "ENH",
				"hotCityFlag": null,
				"py": "Enshi",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e49b0028",
				"text": "二连浩特",
				"countryName": "中国",
				"flightCityCode": "ERL",
				"hotCityFlag": null,
				"py": "ErLianHaoTe",
				"stateName": null
			}],
			"F": [{
				"cityId": "8a88b3ce4ef2ded8014ef2e0e49c0029",
				"text": "佛山",
				"countryName": "中国",
				"flightCityCode": "FUO",
				"hotCityFlag": null,
				"py": "Foshan",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e49c002a",
				"text": "福州",
				"countryName": "中国",
				"flightCityCode": "FOC",
				"hotCityFlag": null,
				"py": "Fuzhou",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e49d002b",
				"text": "阜阳",
				"countryName": "中国",
				"flightCityCode": "FUG",
				"hotCityFlag": null,
				"py": "Fuyang",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e49e002c",
				"text": "富蕴",
				"countryName": "中国",
				"flightCityCode": "FYN",
				"hotCityFlag": null,
				"py": "Fuyun",
				"stateName": null
			}],
			"G": [{
				"cityId": "8a88b3ce4ef2ded8014ef2e0e49e002d",
				"text": "赣州",
				"countryName": "中国",
				"flightCityCode": "KOW",
				"hotCityFlag": null,
				"py": "Ganzhou",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e49f002e",
				"text": "格尔木",
				"countryName": "中国",
				"flightCityCode": "GOQ",
				"hotCityFlag": null,
				"py": "Geermu",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e49f002f",
				"text": "固原",
				"countryName": "中国",
				"flightCityCode": "GYU",
				"hotCityFlag": null,
				"py": "Guyan",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4a00030",
				"text": "光化",
				"countryName": "中国",
				"flightCityCode": "LHK",
				"hotCityFlag": null,
				"py": "GuangHua",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4a00031",
				"text": "广汉",
				"countryName": "中国",
				"flightCityCode": "GHN",
				"hotCityFlag": null,
				"py": "Guanghan",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4a10032",
				"text": "广元",
				"countryName": "中国",
				"flightCityCode": "GYS",
				"hotCityFlag": null,
				"py": "Guangyuan",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4a20033",
				"text": "广州",
				"countryName": "中国",
				"flightCityCode": "CAN",
				"hotCityFlag": null,
				"py": "Guangzhou",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4a20034",
				"text": "贵阳",
				"countryName": "中国",
				"flightCityCode": "KWE",
				"hotCityFlag": null,
				"py": "Guiyang",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4a30035",
				"text": "桂林",
				"countryName": "中国",
				"flightCityCode": "KWL",
				"hotCityFlag": null,
				"py": "Guilin",
				"stateName": null
			}],
			"H": [{
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4a40036",
				"text": "哈尔滨",
				"countryName": "中国",
				"flightCityCode": "HRB",
				"hotCityFlag": null,
				"py": "Haerbing",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4a50037",
				"text": "哈密",
				"countryName": "中国",
				"flightCityCode": "HMI",
				"hotCityFlag": null,
				"py": "Hami",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4a60038",
				"text": "海口",
				"countryName": "中国",
				"flightCityCode": "HAK",
				"hotCityFlag": null,
				"py": "Haikou",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4a60039",
				"text": "海拉尔",
				"countryName": "中国",
				"flightCityCode": "HLD",
				"hotCityFlag": null,
				"py": "Hailaer",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4a7003a",
				"text": "邯郸",
				"countryName": "中国",
				"flightCityCode": "HDG",
				"hotCityFlag": null,
				"py": "Handan",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4a8003b",
				"text": "汉中",
				"countryName": "中国",
				"flightCityCode": "HZG",
				"hotCityFlag": null,
				"py": "Hanzhong",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4a9003c",
				"text": "杭州",
				"countryName": "中国",
				"flightCityCode": "HGH",
				"hotCityFlag": null,
				"py": "Hangzhou",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4a9003d",
				"text": "合肥",
				"countryName": "中国",
				"flightCityCode": "HFE",
				"hotCityFlag": null,
				"py": "Hefei",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4aa003e",
				"text": "和田",
				"countryName": "中国",
				"flightCityCode": "HTN",
				"hotCityFlag": null,
				"py": "Hetian",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4aa003f",
				"text": "黑河",
				"countryName": "中国",
				"flightCityCode": "HEK",
				"hotCityFlag": null,
				"py": "Heihe",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4ab0040",
				"text": "衡阳",
				"countryName": "中国",
				"flightCityCode": "HNY",
				"hotCityFlag": null,
				"py": "Hengyang",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4ab0041",
				"text": "呼和浩特",
				"countryName": "中国",
				"flightCityCode": "HET",
				"hotCityFlag": null,
				"py": "Huhehaote",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4ac0042",
				"text": "怀化(芷江)",
				"countryName": "中国",
				"flightCityCode": "HJJ",
				"hotCityFlag": null,
				"py": "Huaihua",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4ac0043",
				"text": "淮安",
				"countryName": "中国",
				"flightCityCode": "HIA",
				"hotCityFlag": null,
				"py": "HuaiAn",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4ad0044",
				"text": "黄山",
				"countryName": "中国",
				"flightCityCode": "TXN",
				"hotCityFlag": null,
				"py": "Huangshan",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4ae0045",
				"text": "黄岩(台州)",
				"countryName": "中国",
				"flightCityCode": "HYN",
				"hotCityFlag": null,
				"py": "Huangyan",
				"stateName": null
			}],
			"I": null,
			"J": [{
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4ae0046",
				"text": "鸡西",
				"countryName": "中国",
				"flightCityCode": "JXA",
				"hotCityFlag": null,
				"py": "JiXi",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4af0047",
				"text": "吉林",
				"countryName": "中国",
				"flightCityCode": "JIL",
				"hotCityFlag": null,
				"py": "Jilin",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4af0048",
				"text": "济南",
				"countryName": "中国",
				"flightCityCode": "TNA",
				"hotCityFlag": null,
				"py": "Jinan",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4b00049",
				"text": "济宁",
				"countryName": "中国",
				"flightCityCode": "JNG",
				"hotCityFlag": null,
				"py": "Jining",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4b0004a",
				"text": "加格达奇",
				"countryName": "中国",
				"flightCityCode": "JGD",
				"hotCityFlag": null,
				"py": "JiaGeDaQi",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4b1004b",
				"text": "佳木斯",
				"countryName": "中国",
				"flightCityCode": "JMU",
				"hotCityFlag": null,
				"py": "Jiamusi",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4b1004c",
				"text": "嘉峪关",
				"countryName": "中国",
				"flightCityCode": "JGN",
				"hotCityFlag": null,
				"py": "Jiayuguan",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4b2004d",
				"text": "金昌",
				"countryName": "中国",
				"flightCityCode": "JIC",
				"hotCityFlag": null,
				"py": "Jinchang",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4b2004e",
				"text": "锦州",
				"countryName": "中国",
				"flightCityCode": "JNZ",
				"hotCityFlag": null,
				"py": "Jingzhou",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4b3004f",
				"text": "晋江",
				"countryName": "中国",
				"flightCityCode": "JJN",
				"hotCityFlag": null,
				"py": "Jinjiang",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4b30050",
				"text": "井冈山",
				"countryName": "中国",
				"flightCityCode": "JGS",
				"hotCityFlag": null,
				"py": "Jingangshan",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4b40051",
				"text": "景德镇",
				"countryName": "中国",
				"flightCityCode": "JDZ",
				"hotCityFlag": null,
				"py": "Jingdezheng",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4b40052",
				"text": "景洪(西双版纳)",
				"countryName": "中国",
				"flightCityCode": "JHG",
				"hotCityFlag": null,
				"py": "Jinghong",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4b50053",
				"text": "九江",
				"countryName": "中国",
				"flightCityCode": "JIU",
				"hotCityFlag": null,
				"py": "Jiujiang",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4b60054",
				"text": "九寨沟",
				"countryName": "中国",
				"flightCityCode": "JZH",
				"hotCityFlag": null,
				"py": "Jiuzaigou",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4b60055",
				"text": "酒泉",
				"countryName": "中国",
				"flightCityCode": "CHW",
				"hotCityFlag": null,
				"py": "Jiuquan",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4d10084",
				"text": "揭阳潮汕",
				"countryName": "中国",
				"flightCityCode": "SWA",
				"hotCityFlag": null,
				"py": "jieyangchaoshan",
				"stateName": null
			}],
			"K": [{
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4b70056",
				"text": "喀什",
				"countryName": "中国",
				"flightCityCode": "KHG",
				"hotCityFlag": null,
				"py": "Kashi",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4b70057",
				"text": "康定",
				"countryName": "中国",
				"flightCityCode": "KGT",
				"hotCityFlag": null,
				"py": "Kangding",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4b80058",
				"text": "克拉玛依",
				"countryName": "中国",
				"flightCityCode": "KRY",
				"hotCityFlag": null,
				"py": "Kelamayi",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4b80059",
				"text": "库车",
				"countryName": "中国",
				"flightCityCode": "KCA",
				"hotCityFlag": null,
				"py": "Kuche",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4b9005b",
				"text": "昆明",
				"countryName": "中国",
				"flightCityCode": "KMG",
				"hotCityFlag": null,
				"py": "Kunming",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4fe00c6",
				"text": "喀纳斯",
				"countryName": "中国",
				"flightCityCode": "KJI",
				"hotCityFlag": null,
				"py": "Kanas",
				"stateName": null
			}],
			"L": [{
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4b9005a",
				"text": "库尔勒",
				"countryName": "中国",
				"flightCityCode": "KRL",
				"hotCityFlag": null,
				"py": "Luerle",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4ba005c",
				"text": "拉萨",
				"countryName": "中国",
				"flightCityCode": "LXA",
				"hotCityFlag": null,
				"py": "Lasa",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4ba005d",
				"text": "兰州",
				"countryName": "中国",
				"flightCityCode": "LHW",
				"hotCityFlag": null,
				"py": "Lanzhou",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4bb005e",
				"text": "黎平",
				"countryName": "中国",
				"flightCityCode": "HZH",
				"hotCityFlag": null,
				"py": "Lipin",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4bb005f",
				"text": "丽江",
				"countryName": "中国",
				"flightCityCode": "LJG",
				"hotCityFlag": null,
				"py": "Lijiang",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4bc0060",
				"text": "荔波",
				"countryName": "中国",
				"flightCityCode": "LLB",
				"hotCityFlag": null,
				"py": "Libo",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4bc0061",
				"text": "连城",
				"countryName": "中国",
				"flightCityCode": "LCX",
				"hotCityFlag": null,
				"py": "Liancheng",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4bd0062",
				"text": "连云港",
				"countryName": "中国",
				"flightCityCode": "LYG",
				"hotCityFlag": null,
				"py": "Lianyungang",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4bd0063",
				"text": "梁平",
				"countryName": "中国",
				"flightCityCode": "LIA",
				"hotCityFlag": null,
				"py": "Liangpin",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4be0064",
				"text": "林西",
				"countryName": "中国",
				"flightCityCode": "LXI",
				"hotCityFlag": null,
				"py": "LinXi",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4be0065",
				"text": "林芝",
				"countryName": "中国",
				"flightCityCode": "LZY",
				"hotCityFlag": null,
				"py": "Linzhi",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4bf0066",
				"text": "临沧",
				"countryName": "中国",
				"flightCityCode": "LNJ",
				"hotCityFlag": null,
				"py": "Lincang",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4bf0067",
				"text": "临沂",
				"countryName": "中国",
				"flightCityCode": "LYI",
				"hotCityFlag": null,
				"py": "Linyi",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4c00068",
				"text": "零凌(永州)",
				"countryName": "中国",
				"flightCityCode": "LLF",
				"hotCityFlag": null,
				"py": "Lingling",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4c10069",
				"text": "柳州",
				"countryName": "中国",
				"flightCityCode": "LZH",
				"hotCityFlag": null,
				"py": "Liuzhou",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4c2006a",
				"text": "泸州",
				"countryName": "中国",
				"flightCityCode": "LZO",
				"hotCityFlag": null,
				"py": "Luzhou",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4c2006b",
				"text": "洛阳",
				"countryName": "中国",
				"flightCityCode": "LYA",
				"hotCityFlag": null,
				"py": "Luoyang",
				"stateName": null
			}],
			"M": [{
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4c3006c",
				"text": "满洲里",
				"countryName": "中国",
				"flightCityCode": "NZH",
				"hotCityFlag": null,
				"py": "Manzhouli",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4c3006d",
				"text": "梅县",
				"countryName": "中国",
				"flightCityCode": "MXZ",
				"hotCityFlag": null,
				"py": "Meixian",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4c4006e",
				"text": "绵阳",
				"countryName": "中国",
				"flightCityCode": "MIG",
				"hotCityFlag": null,
				"py": "Mianyang",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4c4006f",
				"text": "漠河",
				"countryName": "中国",
				"flightCityCode": "OHE",
				"hotCityFlag": null,
				"py": "Mohe",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4c50070",
				"text": "牡丹江",
				"countryName": "中国",
				"flightCityCode": "MDG",
				"hotCityFlag": null,
				"py": "Mudanjiang",
				"stateName": null
			}],
			"N": [{
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4c50071",
				"text": "那拉提",
				"countryName": "中国",
				"flightCityCode": "NLT",
				"hotCityFlag": null,
				"py": "Nalati",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4c60072",
				"text": "南昌",
				"countryName": "中国",
				"flightCityCode": "KHN",
				"hotCityFlag": null,
				"py": "Nanchang",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4c70073",
				"text": "南充",
				"countryName": "中国",
				"flightCityCode": "NAO",
				"hotCityFlag": null,
				"py": "Nanchong",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4c70074",
				"text": "南京",
				"countryName": "中国",
				"flightCityCode": "NKG",
				"hotCityFlag": null,
				"py": "Nanjing",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4c80075",
				"text": "南宁",
				"countryName": "中国",
				"flightCityCode": "NNG",
				"hotCityFlag": null,
				"py": "Nanning",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4c80076",
				"text": "南通",
				"countryName": "中国",
				"flightCityCode": "NTG",
				"hotCityFlag": null,
				"py": "Nantong",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4c90077",
				"text": "南阳",
				"countryName": "中国",
				"flightCityCode": "NNY",
				"hotCityFlag": null,
				"py": "Nanyang",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4c90078",
				"text": "宁波",
				"countryName": "中国",
				"flightCityCode": "NGB",
				"hotCityFlag": null,
				"py": "Ningbo",
				"stateName": null
			}],
			"O": null,
			"P": [{
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4ca0079",
				"text": "攀枝花",
				"countryName": "中国",
				"flightCityCode": "PZI",
				"hotCityFlag": null,
				"py": "Panzhihua",
				"stateName": null
			}],
			"Q": [{
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4cb007a",
				"text": "齐齐哈尔",
				"countryName": "中国",
				"flightCityCode": "NDG",
				"hotCityFlag": null,
				"py": "Qiqihaer",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4cc007b",
				"text": "黔江",
				"countryName": "中国",
				"flightCityCode": "JIQ",
				"hotCityFlag": null,
				"py": "Qianjiang",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4cc007c",
				"text": "且末",
				"countryName": "中国",
				"flightCityCode": "IQM",
				"hotCityFlag": null,
				"py": "Qiemo",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4cd007d",
				"text": "秦皇岛",
				"countryName": "中国",
				"flightCityCode": "SHP",
				"hotCityFlag": null,
				"py": "Qinhuangdao",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4ce007e",
				"text": "青岛",
				"countryName": "中国",
				"flightCityCode": "TAO",
				"hotCityFlag": null,
				"py": "Qingdao",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4ce007f",
				"text": "庆阳",
				"countryName": "中国",
				"flightCityCode": "IQN",
				"hotCityFlag": null,
				"py": "Qingyang",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4cf0080",
				"text": "衢州",
				"countryName": "中国",
				"flightCityCode": "JUZ",
				"hotCityFlag": null,
				"py": "Quzhou",
				"stateName": null
			}],
			"R": [{
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4cf0081",
				"text": "日喀则",
				"countryName": "中国",
				"flightCityCode": "RKZ",
				"hotCityFlag": null,
				"py": "RiKaZe",
				"stateName": null
			}],
			"S": [{
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4d00082",
				"text": "三亚",
				"countryName": "中国",
				"flightCityCode": "SYX",
				"hotCityFlag": null,
				"py": "Sanya",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4d00083",
				"text": "沙市",
				"countryName": "中国",
				"flightCityCode": "SHS",
				"hotCityFlag": null,
				"py": "Shashi",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4d10085",
				"text": "上海",
				"countryName": "中国",
				"flightCityCode": "111",
				"hotCityFlag": null,
				"py": "ShangHai",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4d20086",
				"text": "上海(虹桥)",
				"countryName": "中国",
				"flightCityCode": "SHA",
				"hotCityFlag": null,
				"py": "ShangHaiHongQiao",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4d20087",
				"text": "上海(浦东)",
				"countryName": "中国",
				"flightCityCode": "PVG",
				"hotCityFlag": null,
				"py": "ShangHaiPuDong",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4d30088",
				"text": "韶关",
				"countryName": "中国",
				"flightCityCode": "SHG",
				"hotCityFlag": null,
				"py": "Shaoguan",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4d30089",
				"text": "深圳",
				"countryName": "中国",
				"flightCityCode": "SZX",
				"hotCityFlag": null,
				"py": "Shenzhen",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4d4008a",
				"text": "沈阳",
				"countryName": "中国",
				"flightCityCode": "SHE",
				"hotCityFlag": null,
				"py": "Shenyang",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4d5008b",
				"text": "石家庄",
				"countryName": "中国",
				"flightCityCode": "SJW",
				"hotCityFlag": null,
				"py": "Shijiazhuang",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4d5008c",
				"text": "思茅",
				"countryName": "中国",
				"flightCityCode": "SYM",
				"hotCityFlag": null,
				"py": "Simao",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4d6008d",
				"text": "苏州",
				"countryName": "中国",
				"flightCityCode": "SZV",
				"hotCityFlag": null,
				"py": "Suzhou",
				"stateName": null
			}],
			"T": [{
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4d6008e",
				"text": "塔城",
				"countryName": "中国",
				"flightCityCode": "TCG",
				"hotCityFlag": null,
				"py": "Tacheng",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4d7008f",
				"text": "太原",
				"countryName": "中国",
				"flightCityCode": "TYN",
				"hotCityFlag": null,
				"py": "Taiyuan",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4d70090",
				"text": "唐山",
				"countryName": "中国",
				"flightCityCode": "TVS",
				"hotCityFlag": null,
				"py": "Tangshan",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4d80091",
				"text": "腾冲",
				"countryName": "中国",
				"flightCityCode": "TCZ",
				"hotCityFlag": null,
				"py": "Tengchong",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4d80092",
				"text": "天津",
				"countryName": "中国",
				"flightCityCode": "TSN",
				"hotCityFlag": null,
				"py": "Tianjin",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4d90093",
				"text": "天水",
				"countryName": "中国",
				"flightCityCode": "THQ",
				"hotCityFlag": null,
				"py": "TianShui",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4d90094",
				"text": "通化",
				"countryName": "中国",
				"flightCityCode": "TNH",
				"hotCityFlag": null,
				"py": "Tonghua",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4da0095",
				"text": "通辽",
				"countryName": "中国",
				"flightCityCode": "TGO",
				"hotCityFlag": null,
				"py": "Tongliao",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4da0096",
				"text": "铜仁",
				"countryName": "中国",
				"flightCityCode": "TEN",
				"hotCityFlag": null,
				"py": "Tongren",
				"stateName": null
			}],
			"U": null,
			"V": null,
			"W": [{
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4db0097",
				"text": "万州",
				"countryName": "中国",
				"flightCityCode": "WXN",
				"hotCityFlag": null,
				"py": "Wanzhou",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4db0098",
				"text": "威海",
				"countryName": "中国",
				"flightCityCode": "WEH",
				"hotCityFlag": null,
				"py": "Weihai",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4dc0099",
				"text": "潍坊",
				"countryName": "中国",
				"flightCityCode": "WEF",
				"hotCityFlag": null,
				"py": "Weifang",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4dc009a",
				"text": "温州",
				"countryName": "中国",
				"flightCityCode": "WNZ",
				"hotCityFlag": null,
				"py": "wenzhou",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4dd009b",
				"text": "文山",
				"countryName": "中国",
				"flightCityCode": "WNH",
				"hotCityFlag": null,
				"py": "WenShan",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4dd009c",
				"text": "乌海",
				"countryName": "中国",
				"flightCityCode": "WUA",
				"hotCityFlag": null,
				"py": "Wuhai",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4de009d",
				"text": "乌兰浩特",
				"countryName": "中国",
				"flightCityCode": "HLH",
				"hotCityFlag": null,
				"py": "Wulanhaote",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4df009e",
				"text": "乌鲁木齐",
				"countryName": "中国",
				"flightCityCode": "URC",
				"hotCityFlag": null,
				"py": "Wulumuqi",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4df009f",
				"text": "无锡",
				"countryName": "中国",
				"flightCityCode": "WUX",
				"hotCityFlag": null,
				"py": "Wuxi",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4e000a0",
				"text": "梧州",
				"countryName": "中国",
				"flightCityCode": "WUZ",
				"hotCityFlag": null,
				"py": "Wuzhou",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4e000a1",
				"text": "武汉",
				"countryName": "中国",
				"flightCityCode": "WUH",
				"hotCityFlag": null,
				"py": "Wuhan",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4e100a2",
				"text": "武夷山",
				"countryName": "中国",
				"flightCityCode": "WUS",
				"hotCityFlag": null,
				"py": "Wuyishan",
				"stateName": null
			}],
			"X": [{
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4e100a3",
				"text": "西安",
				"countryName": "中国",
				"flightCityCode": "XIY",
				"hotCityFlag": null,
				"py": "Xian",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4e200a4",
				"text": "西昌",
				"countryName": "中国",
				"flightCityCode": "XIC",
				"hotCityFlag": null,
				"py": "Xichang",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4e300a5",
				"text": "西宁",
				"countryName": "中国",
				"flightCityCode": "XNN",
				"hotCityFlag": null,
				"py": "Xining",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4e300a6",
				"text": "锡林浩特",
				"countryName": "中国",
				"flightCityCode": "XIL",
				"hotCityFlag": null,
				"py": "Xilinhaote",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4e400a7",
				"text": "厦门",
				"countryName": "中国",
				"flightCityCode": "XMN",
				"hotCityFlag": null,
				"py": "Xiamen",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4e500a8",
				"text": "襄樊",
				"countryName": "中国",
				"flightCityCode": "XFN",
				"hotCityFlag": null,
				"py": "Xiangfan",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4e500a9",
				"text": "兴义",
				"countryName": "中国",
				"flightCityCode": "ACX",
				"hotCityFlag": null,
				"py": "Xingyi",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4e600aa",
				"text": "徐州",
				"countryName": "中国",
				"flightCityCode": "XUZ",
				"hotCityFlag": null,
				"py": "Xuzhou",
				"stateName": null
			}],
			"Y": [{
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4e700ab",
				"text": "烟台",
				"countryName": "中国",
				"flightCityCode": "YNT",
				"hotCityFlag": null,
				"py": "Yantai",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4e700ac",
				"text": "延安",
				"countryName": "中国",
				"flightCityCode": "ENY",
				"hotCityFlag": null,
				"py": "Yanan",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4e800ad",
				"text": "延吉",
				"countryName": "中国",
				"flightCityCode": "YNJ",
				"hotCityFlag": null,
				"py": "Yanji",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4e900ae",
				"text": "盐城",
				"countryName": "中国",
				"flightCityCode": "YNZ",
				"hotCityFlag": null,
				"py": "Yancheng",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4ea00af",
				"text": "扬州",
				"countryName": "中国",
				"flightCityCode": "YTY",
				"hotCityFlag": null,
				"py": "Yangzhou",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4eb00b0",
				"text": "伊春",
				"countryName": "中国",
				"flightCityCode": "LDS",
				"hotCityFlag": null,
				"py": "YiChun",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4eb00b1",
				"text": "伊犁",
				"countryName": "中国",
				"flightCityCode": "YIN",
				"hotCityFlag": null,
				"py": "Yili",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4ec00b2",
				"text": "宜宾",
				"countryName": "中国",
				"flightCityCode": "YBP",
				"hotCityFlag": null,
				"py": "Yibin",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4ed00b3",
				"text": "宜昌",
				"countryName": "中国",
				"flightCityCode": "YIH",
				"hotCityFlag": null,
				"py": "Yichang",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4ee00b4",
				"text": "宜春",
				"countryName": "中国",
				"flightCityCode": "YIC",
				"hotCityFlag": null,
				"py": "YiChun",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4ee00b5",
				"text": "义乌",
				"countryName": "中国",
				"flightCityCode": "YIW",
				"hotCityFlag": null,
				"py": "Yiwu",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4ef00b6",
				"text": "银川",
				"countryName": "中国",
				"flightCityCode": "INC",
				"hotCityFlag": null,
				"py": "Yinchuan",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4f000b7",
				"text": "榆林",
				"countryName": "中国",
				"flightCityCode": "UYN",
				"hotCityFlag": null,
				"py": "Yulin",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4f100b8",
				"text": "玉树",
				"countryName": "中国",
				"flightCityCode": "YUS",
				"hotCityFlag": null,
				"py": "Yushu",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4f200b9",
				"text": "运城",
				"countryName": "中国",
				"flightCityCode": "YCU",
				"hotCityFlag": null,
				"py": "Yuncheng",
				"stateName": null
			}],
			"Z": [{
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4f300ba",
				"text": "湛江",
				"countryName": "中国",
				"flightCityCode": "ZHA",
				"hotCityFlag": null,
				"py": "Zhanjiang",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4f400bb",
				"text": "张家界",
				"countryName": "中国",
				"flightCityCode": "DYG",
				"hotCityFlag": null,
				"py": "Zhangjiajie",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4f500bc",
				"text": "张家口",
				"countryName": "中国",
				"flightCityCode": "ZQZ",
				"hotCityFlag": null,
				"py": "ZhangJiaKou",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4f600bd",
				"text": "张掖",
				"countryName": "中国",
				"flightCityCode": "YZY",
				"hotCityFlag": null,
				"py": "Zhangye",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4f700be",
				"text": "昭通",
				"countryName": "中国",
				"flightCityCode": "ZAT",
				"hotCityFlag": null,
				"py": "Zhaotong",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4f800bf",
				"text": "郑州",
				"countryName": "中国",
				"flightCityCode": "CGO",
				"hotCityFlag": null,
				"py": "Zhengzhou",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4f800c0",
				"text": "中山",
				"countryName": "中国",
				"flightCityCode": "ZGN",
				"hotCityFlag": null,
				"py": "ZhongShan",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4f900c1",
				"text": "中卫",
				"countryName": "中国",
				"flightCityCode": "ZHY",
				"hotCityFlag": null,
				"py": "Zhongwei",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4fa00c3",
				"text": "舟山",
				"countryName": "中国",
				"flightCityCode": "HSN",
				"hotCityFlag": null,
				"py": "Zhoushan",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4fb00c4",
				"text": "珠海",
				"countryName": "中国",
				"flightCityCode": "ZUH",
				"hotCityFlag": null,
				"py": "Zhuhai",
				"stateName": null
			}, {
				"cityId": "8a88b3ce4ef2ded8014ef2e0e4fd00c5",
				"text": "遵义",
				"countryName": "中国",
				"flightCityCode": "ZYI",
				"hotCityFlag": null,
				"py": "Zunyi",
				"stateName": null
			}],
			"resultFlag": 1,
			"resultMsg": "成功"
		},
	});
	return webpc;
});